### ISSUE TITLE
can not work in windows 11

### ISSUE THREAD

**Issue by jxxcr** [lf-/ChangeBrightness#2]
can not work in windows 11,

PS >.\ChangeBrightness64.exe -a 100

Relative mode: 0
Brightness change: 100
Ignoring monitor: cannot get brightness: 3223725449

**Comment by lf-** [comment]
Interesting. I don't have a Windows computer anymore so this sounds like high time to archive this repo. I'm not sure what the error is here, but I'm guessing if you modified the code to use FormatMessage to give you the actual meaning of the error it may be enlightening.

**Comment by lf-** [comment]
I converted the error code to hex then googled it and here's a result: https://github.com/emoacht/Monitorian/blob/master/Source/Monitorian.Core/Models/Monitor/MonitorConfiguration.cs#L677

maybe your monitor doesn't support DDC brightness control? it looks like i was lazy and didn't check if monitors have the capability with https://learn.microsoft.com/en-us/windows/win32/api/highlevelmonitorconfigurationapi/nf-highlevelmonitorconfigurationapi-getmonitorcapabilities

anyway, i doubt it's a Windows 11 issue unless proven otherwise, but this software isn't really maintained so I'm going to archive the repo soon.
